framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'orders'
                        type: direct
        routing:
            'App\Notifier\SendOrderEmailNotification': async
